package controller

import (
	"io"
	"net/http"
	"strconv"

	"campus-emergency/model"
	"campus-emergency/service"
	"github.com/gin-gonic/gin"
)

type PlanController struct { planService service.PlanService }
func NewPlanController(planService service.PlanService) *PlanController { return &PlanController{planService: planService} }

type Response struct { Data interface{} `json:"data,omitempty"`; Error string `json:"error,omitempty"` }

func (c *PlanController) CreatePlan(ctx *gin.Context) { var plan model.EmergencyPlan; if err := ctx.ShouldBindJSON(&plan); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的请求数据: " + err.Error()}); return }; plan.CreatorID = 1; plan.CreatorName = "admin"; if err := c.planService.CreatePlan(&plan); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: plan}) }
func (c *PlanController) UpdatePlan(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; var plan model.EmergencyPlan; if err := ctx.ShouldBindJSON(&plan); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的请求数据: " + err.Error()}); return }; plan.ID = uint(id); if err := c.planService.UpdatePlan(&plan); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: plan}) }
func (c *PlanController) DeletePlan(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; if err := c.planService.DeletePlan(uint(id)); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: true}) }
func (c *PlanController) GetPlan(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; plan, err := c.planService.GetPlanByID(uint(id)); if err != nil { ctx.JSON(http.StatusNotFound, Response{Error: "预案不存在"}); return }; ctx.JSON(http.StatusOK, Response{Data: plan}) }
func (c *PlanController) SearchPlans(ctx *gin.Context) { condition := &model.PlanSearchCondition{}; if v := ctx.Query("scenario_type"); v != "" { condition.ScenarioType = v }; if v := ctx.Query("status"); v != "" { condition.Status = model.PlanStatus(v) }; condition.Keyword = ctx.Query("keyword"); condition.Page, _ = strconv.Atoi(ctx.DefaultQuery("page", "1")); condition.PageSize, _ = strconv.Atoi(ctx.DefaultQuery("page_size", "10")); plans, total, err := c.planService.SearchPlans(condition); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: map[string]interface{}{"plans": plans, "total": total, "page": condition.Page, "page_size": condition.PageSize, "total_pages": (total + int64(condition.PageSize) - 1) / int64(condition.PageSize)}}) }
func (c *PlanController) GetPlansByScenarioType(ctx *gin.Context) { plans, err := c.planService.GetPlansByScenarioType(model.ScenarioType(ctx.Param("scenario_type"))); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: plans}) }
func (c *PlanController) UpdatePlanStatus(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; var statusData map[string]string; if err := ctx.ShouldBindJSON(&statusData); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的请求数据: " + err.Error()}); return }; status, ok := statusData["status"]; if !ok { ctx.JSON(http.StatusBadRequest, Response{Error: "缺少状态参数"}); return }; if err := c.planService.UpdatePlanStatus(uint(id), model.PlanStatus(status)); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: true}) }
func (c *PlanController) OptimizePlanPath(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; plan, err := c.planService.OptimizePlanPath(uint(id)); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: plan}) }
func (c *PlanController) ImportPlans(ctx *gin.Context) { file, _, err := ctx.Request.FormFile("file"); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "获取文件失败: " + err.Error()}); return }; defer file.Close(); data, err := io.ReadAll(file); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "读取文件失败: " + err.Error()}); return }; count, err := c.planService.ImportPlans(data, 1, "admin"); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: map[string]int{"imported_count": count}}) }
func (c *PlanController) ExportPlans(ctx *gin.Context) { condition := &model.PlanSearchCondition{}; if v := ctx.Query("scenario_type"); v != "" { condition.ScenarioType = v }; if v := ctx.Query("status"); v != "" { condition.Status = model.PlanStatus(v) }; exportData, err := c.planService.ExportPlans(condition); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, exportData) }
func (c *PlanController) UpdatePath(ctx *gin.Context) { id, err := strconv.ParseUint(ctx.Param("id"), 10, 32); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的预案ID"}); return }; var path []model.PathPoint; if err := ctx.ShouldBindJSON(&path); err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: "无效的请求数据: " + err.Error()}); return }; plan, err := c.planService.UpdatePath(uint(id), path); if err != nil { ctx.JSON(http.StatusBadRequest, Response{Error: err.Error()}); return }; ctx.JSON(http.StatusOK, Response{Data: plan}) }
